# https://dash-overflow.net/articles/getting_started/
include: analysis_options_all.yaml
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    included_file_warning: ignore

linter:
  rules:
