name: flutter_widget_from_html_core
version: 0.3.2+2
description: Flutter plugin for widget tree building from html that focuses on correctness and extensibility.
homepage: https://github.com/daohoangson/flutter_widget_from_html/tree/master/packages/core

environment:
  flutter: ">=1.6.7 <2.0.0"
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  csslib: ^0.16.1
  flutter:
    sdk: flutter
  html: ^0.14.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any

dependency_overrides:
  csslib:
    git:
      url: git://github.com/daohoangson/csslib.git
      ref: bug/color-from-css
